/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WilayahRouteImport } from './routes/wilayah'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WilayahIndexRouteImport } from './routes/wilayah.index'
import { Route as WilayahSlugRouteImport } from './routes/wilayah.$slug'

const WilayahRoute = WilayahRouteImport.update({
  id: '/wilayah',
  path: '/wilayah',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WilayahIndexRoute = WilayahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WilayahRoute,
} as any)
const WilayahSlugRoute = WilayahSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WilayahRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/wilayah': typeof WilayahRouteWithChildren
  '/wilayah/$slug': typeof WilayahSlugRoute
  '/wilayah/': typeof WilayahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/wilayah/$slug': typeof WilayahSlugRoute
  '/wilayah': typeof WilayahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/wilayah': typeof WilayahRouteWithChildren
  '/wilayah/$slug': typeof WilayahSlugRoute
  '/wilayah/': typeof WilayahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/laporan' | '/wilayah' | '/wilayah/$slug' | '/wilayah/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/laporan' | '/wilayah/$slug' | '/wilayah'
  id:
    '__root__' | '/' | '/laporan' | '/wilayah' | '/wilayah/$slug' | '/wilayah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaporanRoute: typeof LaporanRoute
  WilayahRoute: typeof WilayahRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wilayah': {
      id: '/wilayah'
      path: '/wilayah'
      fullPath: '/wilayah'
      preLoaderRoute: typeof WilayahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wilayah/': {
      id: '/wilayah/'
      path: '/'
      fullPath: '/wilayah/'
      preLoaderRoute: typeof WilayahIndexRouteImport
      parentRoute: typeof WilayahRoute
    }
    '/wilayah/$slug': {
      id: '/wilayah/$slug'
      path: '/$slug'
      fullPath: '/wilayah/$slug'
      preLoaderRoute: typeof WilayahSlugRouteImport
      parentRoute: typeof WilayahRoute
    }
  }
}

interface WilayahRouteChildren {
  WilayahSlugRoute: typeof WilayahSlugRoute
  WilayahIndexRoute: typeof WilayahIndexRoute
}

const WilayahRouteChildren: WilayahRouteChildren = {
  WilayahSlugRoute: WilayahSlugRoute,
  WilayahIndexRoute: WilayahIndexRoute,
}

const WilayahRouteWithChildren =
  WilayahRoute._addFileChildren(WilayahRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaporanRoute: LaporanRoute,
  WilayahRoute: WilayahRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
